import type { Metadata } from "next";
import Navbar from "./components/Navbar";
import ApolloCustomProvider from "@/lib/apollo/ApolloCustomProvider";
import TanstackProvider from "@/lib/tanstack/TanstackProvider";
import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pokedex",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloCustomProvider>
          <TanstackProvider>
            <Navbar />
            <main className="py-6 sm:px-6 lg:px-8 min-h-screen">
              {children}
            </main>
            <ToastContainer />
          </TanstackProvider>
        </ApolloCustomProvider>
      </body>
    </html>
  );
}
